# Generated by Django 3.1.6 on 2021-02-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familypost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='FamilyBlog Post', max_length=255),
        ),
    ]
