# Generated by Django 3.1.6 on 2021-02-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familypost', '0003_post_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Coding', max_length=255),
            preserve_default=False,
        ),
    ]
