# Generated by Django 3.1.7 on 2021-02-28 10:34

from django.db import migrations, models
import familypost.models


class Migration(migrations.Migration):

    dependencies = [
        ('familypost', '0007_post_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=familypost.models.user_directory_path),
        ),
    ]
