# Generated by Django 3.1.7 on 2021-03-19 08:19

from django.db import migrations, models
import familypost.models
import familypost.validators


class Migration(migrations.Migration):

    dependencies = [
        ('familypost', '0021_auto_20210318_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to=familypost.models.user_directory_path, validators=[familypost.validators.validate_file_type]),
        ),
    ]
