version: '3.1'

services:

  mysql:
    image: mariadb:10.7.1
    restart: always
    environment:
      MYSQL_USER: yu_no
      MYSQL_PASSWORD: refresh
      MYSQL_ROOT_PASSWORD: refresh
    volumes:
      - ./mysql:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
    #ports:
    #  - "3306:3306"
    container_name: mysql

  db-adminer:
    image: adminer
    restart: always
    depends_on:
      - "mysql"
    ports:
      - 8000:8080
    container_name: mysql_admin

  redis:
    image: redis:6.2-rc2
    restart: always
    volumes:
      - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis

  django-dev:
    image: django-working
    command: python manage.py runserver 0.0.0.0:8000
    #command: python
    restart: always
    environment:
      - DATABASE_URL
    volumes:
      - ./src:/setup
      - /var/www/html/familypost/media:/setup/media
      - ./logs:/usr/local/log
    ports: 
      - "9011:8000"
    depends_on: 
      - mysql
    container_name: django

networks:
  default:
    external:
      name: dev_network
